[package]
name = "balance_check"
type = "bin"
authors = [""]

[dependencies]
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
ecrecover = { tag = "v1.0.0", git = "https://github.com/colinnielsen/ecrecover-noir/" }